<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class CancelCashtray extends TestCase
{
    public function testCancelCashtray0()
    {
        $client = $this->newClient();
        $request = new Request\CancelCashtray(
            "1cb4ca07-29ff-4a9e-b608-9714163d2bb4"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
