<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class CreateExchangeTransaction extends TestCase
{
    public function testCreateExchangeTransaction0()
    {
        $client = $this->newClient();
        $request = new Request\CreateExchangeTransaction(
            "2b5af512-79b7-4b27-bb7d-404b2d1ca896",
            "fe338e62-6c52-41a9-b614-ac0d1ad78ba1",
            "c5de1a6b-1bb5-4949-9e6c-f16976521e96",
            2697
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateExchangeTransaction1()
    {
        $client = $this->newClient();
        $request = new Request\CreateExchangeTransaction(
            "2b5af512-79b7-4b27-bb7d-404b2d1ca896",
            "fe338e62-6c52-41a9-b614-ac0d1ad78ba1",
            "c5de1a6b-1bb5-4949-9e6c-f16976521e96",
            2697,
            [
                'description' => "NbGKkdvU0v3FrHNfnAYWXTggV8uLXVPHrvrxHRwoUZXa5PtszGysSR0ABnIxfv879nP49i1HynW3GTzsvMFYcJ34IAnrJHiTqTE0p7qjxtfJwVPsRROrLz8mjzruaw2vFAFHJYo4l"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
