<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class CreateTransaction extends TestCase
{
    public function testCreateTransaction0()
    {
        $client = $this->newClient();
        $request = new Request\CreateTransaction("66f4d5c0-1167-484e-8aba-cadcbca5f5d7", "967099f5-a088-4a9c-943d-076c21a1475c", "f878d8e3-2def-45c1-82bf-36ff759bf263");
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateTransaction1()
    {
        $client = $this->newClient();
        $request = new Request\CreateTransaction("66f4d5c0-1167-484e-8aba-cadcbca5f5d7", "967099f5-a088-4a9c-943d-076c21a1475c", "f878d8e3-2def-45c1-82bf-36ff759bf263", ['description' => "9FsA4xVkinCOK5mKZiXucEAUJnF0WJvkdWKsQJ7p6HQiHkNALJNp2qPiam7MKBqRO6i8PsKFJSqPJoSN1srQ5TGYqpncWbcLUaRkKX8k2u3kXK4Q"]);
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateTransaction2()
    {
        $client = $this->newClient();
        $request = new Request\CreateTransaction("66f4d5c0-1167-484e-8aba-cadcbca5f5d7", "967099f5-a088-4a9c-943d-076c21a1475c", "f878d8e3-2def-45c1-82bf-36ff759bf263", ['point_amount' => 3923, 'description' => "Uj"]);
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateTransaction3()
    {
        $client = $this->newClient();
        $request = new Request\CreateTransaction("66f4d5c0-1167-484e-8aba-cadcbca5f5d7", "967099f5-a088-4a9c-943d-076c21a1475c", "f878d8e3-2def-45c1-82bf-36ff759bf263", ['money_amount' => 2155, 'point_amount' => 3334, 'description' => "SRWAY85TcomAaxSlCiOV5QRYStDTrENgLQKKR947VvkMttH8SdB4w51NwZPncusZzHj8rlVnHkfFKQVmTYpm4AwikQ"]);
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
