<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class CreateTopupTransactionWithCheck extends TestCase
{
    public function testCreateTopupTransactionWithCheck0()
    {
        $client = $this->newClient();
        $request = new Request\CreateTopupTransactionWithCheck("b3d4a6ca-906a-480e-b1a3-29ad15c73207", "4b9f9d41-3d8a-48c4-8a88-1ec3df46d9ad");
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
