<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class CreateUserAccount extends TestCase
{
    public function testCreateUserAccount0()
    {
        $client = $this->newClient();
        $request = new Request\CreateUserAccount(
            "64c5c062-5e26-4008-8194-a297995e0e47",
            "9f8a0db0-2b39-45a1-a809-c29c9784dd42"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateUserAccount1()
    {
        $client = $this->newClient();
        $request = new Request\CreateUserAccount(
            "64c5c062-5e26-4008-8194-a297995e0e47",
            "9f8a0db0-2b39-45a1-a809-c29c9784dd42",
            [
                'metadata' => "{\"key1\":\"foo\",\"key2\":\"bar\"}"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateUserAccount2()
    {
        $client = $this->newClient();
        $request = new Request\CreateUserAccount(
            "64c5c062-5e26-4008-8194-a297995e0e47",
            "9f8a0db0-2b39-45a1-a809-c29c9784dd42",
            [
                'external_id' => "pUJPdIlUSFGcALOoiXWZwUXALsfjg1JhvNP2Dy8DZeE1An",
                'metadata' => "{\"key1\":\"foo\",\"key2\":\"bar\"}"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateUserAccount3()
    {
        $client = $this->newClient();
        $request = new Request\CreateUserAccount(
            "64c5c062-5e26-4008-8194-a297995e0e47",
            "9f8a0db0-2b39-45a1-a809-c29c9784dd42",
            [
                'name' => "47tYXZGpLs77iQOzDAvko6nzClo5Yf3H1E1KAPMEbcHYVKXsvrH6tSb3nTy0mX4fyu",
                'external_id' => "pt4JCoBoE3MSL3OM6bTkL1PMVCokZ",
                'metadata' => "{\"key1\":\"foo\",\"key2\":\"bar\"}"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
