<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class CreateBankTopupTransaction extends TestCase
{
    public function testCreateBankTopupTransaction0()
    {
        $client = $this->newClient();
        $request = new Request\CreateBankTopupTransaction(
            "a2caf645-c346-431d-a4f2-000f00a6f176",
            "4c0009ef-f296-4117-a2b4-98bc3219c2bb",
            3763,
            "d3d22db7-c5c9-4c12-a5d3-b65e17755b95",
            "006318bd-c7c2-4c05-b9f5-1a5ec665e124"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
