<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class CreateOrganization extends TestCase
{
    public function testCreateOrganization0()
    {
        $client = $this->newClient();
        $request = new Request\CreateOrganization(
            "VPZadCz2",
            "1oTLg0Zh082rSUmgTJgltXUvopMAE6nKVgCC79b4Ei190OQ71CLczodkHUHlo8UiDVjyL8K2mxNxSNDBAB21jRDnDfUt4YgIyZaTsiHOmcCShoExxXDzwmu0NmtxroKVUk7sDu4lw8ZxL5ooBCUmbexH",
            ["9dc9069c-3bec-40bc-a44f-e83fbb943159", "6c56b4d0-957f-4364-9da3-805245fa4100", "a741e15f-c3c4-4852-98e6-b1630f98267c", "937597c6-f4c5-4acb-bd29-557d254a3965", "126abb86-e420-4362-903e-26c1a79113c8", "3b50847b-f1a3-4f2d-99e9-b79829459ebf", "7c9467e1-4560-458a-b4ab-b7e0274bba98"],
            "KRmL7K8IMJ@IBW1.com",
            "vB1RC8WQ75@Zq2C.com"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateOrganization1()
    {
        $client = $this->newClient();
        $request = new Request\CreateOrganization(
            "VPZadCz2",
            "1oTLg0Zh082rSUmgTJgltXUvopMAE6nKVgCC79b4Ei190OQ71CLczodkHUHlo8UiDVjyL8K2mxNxSNDBAB21jRDnDfUt4YgIyZaTsiHOmcCShoExxXDzwmu0NmtxroKVUk7sDu4lw8ZxL5ooBCUmbexH",
            ["9dc9069c-3bec-40bc-a44f-e83fbb943159", "6c56b4d0-957f-4364-9da3-805245fa4100", "a741e15f-c3c4-4852-98e6-b1630f98267c", "937597c6-f4c5-4acb-bd29-557d254a3965", "126abb86-e420-4362-903e-26c1a79113c8", "3b50847b-f1a3-4f2d-99e9-b79829459ebf", "7c9467e1-4560-458a-b4ab-b7e0274bba98"],
            "KRmL7K8IMJ@IBW1.com",
            "vB1RC8WQ75@Zq2C.com",
            [
                'contact_name' => "Eph5LyiHrKKZHYeA6KMsRSBkbfNhFwjSSUkqouGV2ULftf3KLiOm0u6OdTYvY1WMa6BMdHbor9Bi8VjYjeAF8N8XvRYyNjj6LzPNoFY0NPc7gW3tdaerbfAUj6MGuDCQRgbbh69IfOOqdFvcvTYHWhMSc2JtDSCuxpXIBKjX0wbEINtuhWyJmxhctiEpL1KlL20SY28CEIpXvCz2l"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateOrganization2()
    {
        $client = $this->newClient();
        $request = new Request\CreateOrganization(
            "VPZadCz2",
            "1oTLg0Zh082rSUmgTJgltXUvopMAE6nKVgCC79b4Ei190OQ71CLczodkHUHlo8UiDVjyL8K2mxNxSNDBAB21jRDnDfUt4YgIyZaTsiHOmcCShoExxXDzwmu0NmtxroKVUk7sDu4lw8ZxL5ooBCUmbexH",
            ["9dc9069c-3bec-40bc-a44f-e83fbb943159", "6c56b4d0-957f-4364-9da3-805245fa4100", "a741e15f-c3c4-4852-98e6-b1630f98267c", "937597c6-f4c5-4acb-bd29-557d254a3965", "126abb86-e420-4362-903e-26c1a79113c8", "3b50847b-f1a3-4f2d-99e9-b79829459ebf", "7c9467e1-4560-458a-b4ab-b7e0274bba98"],
            "KRmL7K8IMJ@IBW1.com",
            "vB1RC8WQ75@Zq2C.com",
            [
                'bank_account_holder_name' => "｢",
                'contact_name' => "WFgkUTJYHHOr63hjnglJCcSZdRjCOwyap0lsb8d4Dc5yMU1TN0yX6wxY6IPoPyEr8klncfGkEwHBWOqOmjPQjCJIqduyEzfF4ihEMnqIdNLL8T5msTmgqj81RXJ34GFY2SrpQfm9Le0rSPWlrPa8fbLwdjVaS9JydpHqXjqW"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateOrganization3()
    {
        $client = $this->newClient();
        $request = new Request\CreateOrganization(
            "VPZadCz2",
            "1oTLg0Zh082rSUmgTJgltXUvopMAE6nKVgCC79b4Ei190OQ71CLczodkHUHlo8UiDVjyL8K2mxNxSNDBAB21jRDnDfUt4YgIyZaTsiHOmcCShoExxXDzwmu0NmtxroKVUk7sDu4lw8ZxL5ooBCUmbexH",
            ["9dc9069c-3bec-40bc-a44f-e83fbb943159", "6c56b4d0-957f-4364-9da3-805245fa4100", "a741e15f-c3c4-4852-98e6-b1630f98267c", "937597c6-f4c5-4acb-bd29-557d254a3965", "126abb86-e420-4362-903e-26c1a79113c8", "3b50847b-f1a3-4f2d-99e9-b79829459ebf", "7c9467e1-4560-458a-b4ab-b7e0274bba98"],
            "KRmL7K8IMJ@IBW1.com",
            "vB1RC8WQ75@Zq2C.com",
            [
                'bank_account' => "5373940",
                'bank_account_holder_name' => "(",
                'contact_name' => "3Z7gIcLSudPl4JIrQm"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateOrganization4()
    {
        $client = $this->newClient();
        $request = new Request\CreateOrganization(
            "VPZadCz2",
            "1oTLg0Zh082rSUmgTJgltXUvopMAE6nKVgCC79b4Ei190OQ71CLczodkHUHlo8UiDVjyL8K2mxNxSNDBAB21jRDnDfUt4YgIyZaTsiHOmcCShoExxXDzwmu0NmtxroKVUk7sDu4lw8ZxL5ooBCUmbexH",
            ["9dc9069c-3bec-40bc-a44f-e83fbb943159", "6c56b4d0-957f-4364-9da3-805245fa4100", "a741e15f-c3c4-4852-98e6-b1630f98267c", "937597c6-f4c5-4acb-bd29-557d254a3965", "126abb86-e420-4362-903e-26c1a79113c8", "3b50847b-f1a3-4f2d-99e9-b79829459ebf", "7c9467e1-4560-458a-b4ab-b7e0274bba98"],
            "KRmL7K8IMJ@IBW1.com",
            "vB1RC8WQ75@Zq2C.com",
            [
                'bank_account_type' => "saving",
                'bank_account' => "837290",
                'bank_account_holder_name' => "ｦ",
                'contact_name' => "uIsMTYyCUoOEa9YZaUNPTMagDSPeHLGCGYvgqbqCIdoPTyGfjAlvbOwBRftL3mTfJhTjDs9c8QNUGvnht1UycVdhwjqe7Rve16qe5BUa3m"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateOrganization5()
    {
        $client = $this->newClient();
        $request = new Request\CreateOrganization(
            "VPZadCz2",
            "1oTLg0Zh082rSUmgTJgltXUvopMAE6nKVgCC79b4Ei190OQ71CLczodkHUHlo8UiDVjyL8K2mxNxSNDBAB21jRDnDfUt4YgIyZaTsiHOmcCShoExxXDzwmu0NmtxroKVUk7sDu4lw8ZxL5ooBCUmbexH",
            ["9dc9069c-3bec-40bc-a44f-e83fbb943159", "6c56b4d0-957f-4364-9da3-805245fa4100", "a741e15f-c3c4-4852-98e6-b1630f98267c", "937597c6-f4c5-4acb-bd29-557d254a3965", "126abb86-e420-4362-903e-26c1a79113c8", "3b50847b-f1a3-4f2d-99e9-b79829459ebf", "7c9467e1-4560-458a-b4ab-b7e0274bba98"],
            "KRmL7K8IMJ@IBW1.com",
            "vB1RC8WQ75@Zq2C.com",
            [
                'bank_branch_code' => "",
                'bank_account_type' => "other",
                'bank_account' => "642904",
                'bank_account_holder_name' => "6",
                'contact_name' => "5nebRZC0vDYNEWMfxXSVHRY4YZdsEswklf9tWgAr9KxjsUzeefEvU98BI4BdtnYVFOF5IXA6lNw66Yqs62ry4EX0H5SsjBGi2vt3IVL"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateOrganization6()
    {
        $client = $this->newClient();
        $request = new Request\CreateOrganization(
            "VPZadCz2",
            "1oTLg0Zh082rSUmgTJgltXUvopMAE6nKVgCC79b4Ei190OQ71CLczodkHUHlo8UiDVjyL8K2mxNxSNDBAB21jRDnDfUt4YgIyZaTsiHOmcCShoExxXDzwmu0NmtxroKVUk7sDu4lw8ZxL5ooBCUmbexH",
            ["9dc9069c-3bec-40bc-a44f-e83fbb943159", "6c56b4d0-957f-4364-9da3-805245fa4100", "a741e15f-c3c4-4852-98e6-b1630f98267c", "937597c6-f4c5-4acb-bd29-557d254a3965", "126abb86-e420-4362-903e-26c1a79113c8", "3b50847b-f1a3-4f2d-99e9-b79829459ebf", "7c9467e1-4560-458a-b4ab-b7e0274bba98"],
            "KRmL7K8IMJ@IBW1.com",
            "vB1RC8WQ75@Zq2C.com",
            [
                'bank_branch_name' => "ujfoeXIyA6Ao821XE55hc29pv4sZBooZY5wA4Og2kdAYLVTxSOsaSsUmdY0CLcfo",
                'bank_branch_code' => "562",
                'bank_account_type' => "current",
                'bank_account' => "1998038",
                'bank_account_holder_name' => " ",
                'contact_name' => "C6o"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateOrganization7()
    {
        $client = $this->newClient();
        $request = new Request\CreateOrganization(
            "VPZadCz2",
            "1oTLg0Zh082rSUmgTJgltXUvopMAE6nKVgCC79b4Ei190OQ71CLczodkHUHlo8UiDVjyL8K2mxNxSNDBAB21jRDnDfUt4YgIyZaTsiHOmcCShoExxXDzwmu0NmtxroKVUk7sDu4lw8ZxL5ooBCUmbexH",
            ["9dc9069c-3bec-40bc-a44f-e83fbb943159", "6c56b4d0-957f-4364-9da3-805245fa4100", "a741e15f-c3c4-4852-98e6-b1630f98267c", "937597c6-f4c5-4acb-bd29-557d254a3965", "126abb86-e420-4362-903e-26c1a79113c8", "3b50847b-f1a3-4f2d-99e9-b79829459ebf", "7c9467e1-4560-458a-b4ab-b7e0274bba98"],
            "KRmL7K8IMJ@IBW1.com",
            "vB1RC8WQ75@Zq2C.com",
            [
                'bank_code' => "",
                'bank_branch_name' => "pSw3LnpbrPkZnNjPWO55",
                'bank_branch_code' => "571",
                'bank_account_type' => "saving",
                'bank_account' => "775",
                'bank_account_holder_name' => ".",
                'contact_name' => "vR52CgIBy3eLTys12HHDFFeqLoUtYmfM0XLYceQxhubY3jVYhbh4RW4SjcPHu2gIp7HlCgxYlFZzBuHZ8tjsh68ScZg3aAMErPcV9o0TcGJkIJgRMahTjY4B83KCbssdnciBK2yKUyBpazsFHLyPhoCqWWrzikH0DrThI9ndCARX9iZhUIwUrsQ8Uijo55dyiBxXbKWYhq"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateOrganization8()
    {
        $client = $this->newClient();
        $request = new Request\CreateOrganization(
            "VPZadCz2",
            "1oTLg0Zh082rSUmgTJgltXUvopMAE6nKVgCC79b4Ei190OQ71CLczodkHUHlo8UiDVjyL8K2mxNxSNDBAB21jRDnDfUt4YgIyZaTsiHOmcCShoExxXDzwmu0NmtxroKVUk7sDu4lw8ZxL5ooBCUmbexH",
            ["9dc9069c-3bec-40bc-a44f-e83fbb943159", "6c56b4d0-957f-4364-9da3-805245fa4100", "a741e15f-c3c4-4852-98e6-b1630f98267c", "937597c6-f4c5-4acb-bd29-557d254a3965", "126abb86-e420-4362-903e-26c1a79113c8", "3b50847b-f1a3-4f2d-99e9-b79829459ebf", "7c9467e1-4560-458a-b4ab-b7e0274bba98"],
            "KRmL7K8IMJ@IBW1.com",
            "vB1RC8WQ75@Zq2C.com",
            [
                'bank_name' => "QcADAJhWFw",
                'bank_code' => "1637",
                'bank_branch_name' => "l2hGkEzja1NmQHCUATGGz590dtBhucZ4e0BzAWy80f2Mm",
                'bank_branch_code' => "",
                'bank_account_type' => "saving",
                'bank_account' => "22902",
                'bank_account_holder_name' => " ",
                'contact_name' => "msbpR1t9xme9U0GR2pRvNpULEoTr6H5p2Y5YBaOZdS1seolNILNbVpFGvZ3N4x3uvaLnbw12Ii4C82SzJJG4lODNS2Ij7U5b72UTWbjXGfzCmZ2vkYmrCrWwA7IkDmk9acr8tX9JQSHyiFoseHqYyK8GIOW0PGU45uzPdd0dJeNNvUC0bqs1hvmd5I8evbrAQGpnYomE2cpD4cThkIOO2LW0e3G1sTmjj"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
