<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class CreateBill extends TestCase
{
    public function testCreateBill0()
    {
        $client = $this->newClient();
        $request = new Request\CreateBill(
            "1da1eb86-d002-4e7c-bd4f-67d70661f61d",
            "b59e34e2-2d0f-44f1-9aaa-9d24179c5a26"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateBill1()
    {
        $client = $this->newClient();
        $request = new Request\CreateBill(
            "1da1eb86-d002-4e7c-bd4f-67d70661f61d",
            "b59e34e2-2d0f-44f1-9aaa-9d24179c5a26",
            [
                'description' => "qVG"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testCreateBill2()
    {
        $client = $this->newClient();
        $request = new Request\CreateBill(
            "1da1eb86-d002-4e7c-bd4f-67d70661f61d",
            "b59e34e2-2d0f-44f1-9aaa-9d24179c5a26",
            [
                'amount' => 9629.0,
                'description' => "NOP2f7Fmc6XSXXM3Y5XPxnjFhfkfYgvABxRhjV7rXm6F6onhtgkbe1I3fnSrAjiMpnuQgQNZWqLAFAWqZBqyjs43AAjN"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
