<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class DeleteAccount extends TestCase
{
    public function testDeleteAccount0()
    {
        $client = $this->newClient();
        $request = new Request\DeleteAccount(
            "ce348e12-e7ee-4579-a9c8-94dd3d6c2f3d"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testDeleteAccount1()
    {
        $client = $this->newClient();
        $request = new Request\DeleteAccount(
            "ce348e12-e7ee-4579-a9c8-94dd3d6c2f3d",
            [
                'cashback' => TRUE
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
