<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class GetCvsAuthorization extends TestCase
{
    public function testGetCvsAuthorization0()
    {
        $client = $this->newClient();
        $request = new Request\GetCvsAuthorization(
            "522a064a-5211-4e9c-a36a-d4150f829256"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
