<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class GetExternalTransactionByRequestId extends TestCase
{
    public function testGetExternalTransactionByRequestId0()
    {
        $client = $this->newClient();
        $request = new Request\GetExternalTransactionByRequestId(
            "6b7a04ad-85a9-4b1b-9a80-e539aca2378a"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
