<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class ListTransfersV2 extends TestCase
{
    public function testListTransfersV20()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2();
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV21()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'to' => "2021-07-23T21:15:26.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV22()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'from' => "2023-09-02T12:57:56.000000Z",
                'to' => "2020-03-09T09:40:54.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV23()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'description' => "AuXzcUztcjpDcIzv8TjKb1dIcQKtgPEpt9Ynsu0LI4T70lQwB453YpOK96EoFGxVJNTeRlFM4Xw2YneFRtau24yc1kusN7qW2yhhPFbHNPhRgnqYnUl",
                'from' => "2022-10-12T10:24:40.000000Z",
                'to' => "2020-12-11T11:18:22.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV24()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'transfer_types' => ["payment", "campaign", "coupon"],
                'description' => "5jFwrAdcz57ZOWsDr0Djt9M12BOno1AcjM96oftC7mHhiSDgXKvVy5paxKD2XcOfyMo26iqol80j1t4n3lpnoezOx6Ov6eGwjQCqxdtQnDY4S9N4HhJ5rCsXRcUZY47cpIh03BvqB7CzLjYHoO28zEE65UlKtMCe12MUV2dxrA24",
                'from' => "2022-05-18T05:03:23.000000Z",
                'to' => "2021-09-13T23:52:18.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV25()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'per_page' => 918,
                'transfer_types' => ["cashback", "expire", "exchange"],
                'description' => "ZLX87qtedPzV8NdiYCu",
                'from' => "2023-03-10T16:06:25.000000Z",
                'to' => "2024-10-14T08:27:30.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV26()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'prev_page_cursor_id' => "149d822c-647c-42e3-9d3e-7c6dc03f08d6",
                'per_page' => 829,
                'transfer_types' => ["topup", "exchange", "campaign", "transfer", "cashback", "payment", "coupon"],
                'description' => "wMWHgQ0VESfspW9b9NBdczTSynCfTiWLEN2pEbq7ZeB8PVJkE9NzaeTptZ5kX9rLpagdWQnEnTlLyubwibc5uG9Y4cn6ApRZ5NX6gFb5nuODlmm9rpn022H3wQmNFzbLFmfFSz1uperYHhU5vbLxW8Yq",
                'from' => "2023-02-02T21:48:08.000000Z",
                'to' => "2022-09-16T00:44:43.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV27()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'next_page_cursor_id' => "78b213dd-1e1f-4e1c-b558-71f09deb442e",
                'prev_page_cursor_id' => "81621452-8975-405d-b538-b83916546e71",
                'per_page' => 180,
                'transfer_types' => ["payment", "expire"],
                'description' => "iRPYO2oQiAYMcKkXBWEu4RSjxgCW3jFlgob7yobgqdqFleVhpCebdmmx3jJLFYo72YjP5pod5QaLCZTmFLxumOnvrupx16EXCUXyPfCabjEtMliIf7wKoPmNQWU6zl3h0ZGoCe5IIfEbaRlpdhTTQpQoSRT6b0I",
                'from' => "2024-08-01T06:19:05.000000Z",
                'to' => "2023-03-17T07:43:22.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV28()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'transaction_types' => ["topup", "cashback", "expire", "exchange", "payment"],
                'next_page_cursor_id' => "062d3c3a-1429-4602-b36a-93a18ee414d3",
                'prev_page_cursor_id' => "bd82a17f-57ac-40f9-ada9-4b1b54747b1a",
                'per_page' => 129,
                'transfer_types' => ["payment", "transfer", "exchange", "topup", "expire", "coupon", "cashback"],
                'description' => "q8yjjxInoBnLVw5NxHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQv",
                'from' => "2023-10-30T19:14:11.000000Z",
                'to' => "2022-04-16T21:31:39.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV29()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'is_modified' => FALSE,
                'transaction_types' => ["topup", "expire", "exchange"],
                'next_page_cursor_id' => "f344eea9-76ca-4c37-9a77-6ea01c07a8ed",
                'prev_page_cursor_id' => "43d150e7-ce14-4d13-831e-430e0a9b203b",
                'per_page' => 344,
                'transfer_types' => ["cashback", "coupon", "payment", "expire"],
                'description' => "enxAKZBD2FhNoFZKIbAgSoRCKxxDEWQZO9yz4Mc4BWxPS7UaVHpVi4pZYZOGKLSewvJuaN97ObUNQZ0A0Rwk2Z2omGatDjCcJfOMaGd4kHySUJYrKI48UyLazcdaqg9M",
                'from' => "2021-10-22T10:47:21.000000Z",
                'to' => "2024-12-09T03:11:30.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV210()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'private_money_id' => "4db002b5-74b6-4ed6-9551-1bfb7532b07a",
                'is_modified' => FALSE,
                'transaction_types' => ["transfer", "exchange", "cashback", "topup", "expire"],
                'next_page_cursor_id' => "f0d8b57d-10a9-4520-9f86-b982ce0c4df2",
                'prev_page_cursor_id' => "edd2359e-2edf-44b7-a6f3-e2426312baee",
                'per_page' => 936,
                'transfer_types' => ["topup", "expire", "payment", "cashback", "transfer", "coupon", "campaign"],
                'description' => "OVY8vi9Z9lrbTGfh4QbdPS2DfLew9jsvLcXjFRqAsdyU0EjzFGdoCEVoN09yrlyTlHcxkp2hdiJWs83eoAqvgg01zZW75gRDgWRTNwobRsB1baR1aePdc",
                'from' => "2020-05-30T21:00:56.000000Z",
                'to' => "2024-07-23T16:51:13.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV211()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'transaction_id' => "9431edff-9699-4885-a610-9882ba1a9aff",
                'private_money_id' => "681eb3a8-1a3f-4e13-9847-18c80a156ecc",
                'is_modified' => FALSE,
                'transaction_types' => ["exchange", "cashback", "expire", "payment", "topup"],
                'next_page_cursor_id' => "b0c1e7e5-413f-452b-a2a9-23a6824a5f6c",
                'prev_page_cursor_id' => "f879ece0-6b5b-4ac1-bbe7-8e9d294cd196",
                'per_page' => 54,
                'transfer_types' => ["payment"],
                'description' => "EeO7nUDqxXj74j643AIOVakyq8QHWKNric3MBQYWsKtvnxoQJLloM94TQVFchkaVLnKXq1JcpZfZUH2UsKCxnRcuSoLNAly4QR5kzfucn7LZFZwhy5RIJGwbFSZ2qU3L9frpqlrETgz3",
                'from' => "2020-10-17T00:26:33.000000Z",
                'to' => "2020-05-12T09:22:52.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV212()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'customer_name' => "Q0TWfR4Gx21zM7WIQGDsPsJyAShBlCJPjtVj6RA58jW2j8noWbhryHKQAP2bBeZkmIh2UeN7Z047tEp9MnaMKkPTTOh4KlFXKgtixsqVTYrrSHZ1a0tz4Ezkuh",
                'transaction_id' => "4bdc057b-9489-4c1d-9a55-db28d89f4143",
                'private_money_id' => "26d3bcbe-c102-40c8-8757-2cf017fd56b8",
                'is_modified' => TRUE,
                'transaction_types' => ["cashback", "transfer", "topup"],
                'next_page_cursor_id' => "ff510af9-6f41-4d02-99d9-d85759bde39d",
                'prev_page_cursor_id' => "ba7f7d83-99bf-4ed5-a64a-bbd748d23673",
                'per_page' => 501,
                'transfer_types' => ["payment", "exchange", "expire", "cashback"],
                'description' => "HOt0XiM6Qkur8SbZd3wcuCesxkTgeUlIAlQvL5t780R",
                'from' => "2023-07-14T14:42:00.000000Z",
                'to' => "2022-10-07T19:00:46.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV213()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'customer_id' => "cd35634c-b012-4135-96f2-844cd5b35d78",
                'customer_name' => "zR",
                'transaction_id' => "fbfdd789-3283-4c51-923c-496c3d687756",
                'private_money_id' => "cbf66c75-f78a-4d24-afb0-47dcc23bbeac",
                'is_modified' => TRUE,
                'transaction_types' => ["topup", "expire"],
                'next_page_cursor_id' => "ec8c27d7-f59b-4927-a4d0-a0dd9c7bb5d5",
                'prev_page_cursor_id' => "d648ee98-8be9-4d00-8aba-8656c39847ac",
                'per_page' => 702,
                'transfer_types' => ["campaign", "topup", "coupon", "exchange", "payment", "transfer"],
                'description' => "cQVtlOjSB31Mxq8SXpxSHJRZi52y7KvoeklIR5ig74Fkbtbb0SlK2KbT8BQ8WxGHxi6f0cuW1ZhxLtCHC",
                'from' => "2021-01-06T13:58:19.000000Z",
                'to' => "2022-05-11T22:33:05.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV214()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'shop_name' => "7yUfJm7Fg98YgjSKRGLQpNx8ciNrKweGJ",
                'customer_id' => "5bce0974-366e-45c7-b1ae-961bda97a72a",
                'customer_name' => "dSp90ci6D0iGddOVzLT6tirwJLurByrAGws",
                'transaction_id' => "791774fa-2156-48bb-9c77-7dad954c026c",
                'private_money_id' => "7ba8fb51-4f41-4912-be75-cf54138c8358",
                'is_modified' => TRUE,
                'transaction_types' => ["cashback", "expire", "exchange"],
                'next_page_cursor_id' => "82dc7228-6e5e-40d9-859e-ca0ce274e08c",
                'prev_page_cursor_id' => "e5052d06-d242-4135-9978-678999a77456",
                'per_page' => 298,
                'transfer_types' => ["cashback", "payment", "exchange"],
                'description' => "VYsbDyysRisRQ9ectqoj4yKOsEPCrpQPvSjUDltH57ysDpO4lTbJ9dqwKn5NSHIJ7mbc5qbOnYCYxA4AjI47p6qtIsaCpt80GzH1FRWe6zLcwMHaeJGFXqwAY75stQD6SAh41f",
                'from' => "2022-07-21T23:24:45.000000Z",
                'to' => "2022-10-22T21:38:34.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testListTransfersV215()
    {
        $client = $this->newClient();
        $request = new Request\ListTransfersV2(
            [
                'shop_id' => "b892eae9-c35f-4040-ba29-931608b591e9",
                'shop_name' => "84vybd1",
                'customer_id' => "a5acbb4a-d173-4b66-b07f-99ea1931a982",
                'customer_name' => "R3rzbwtxyn2FAh1zUedGEpNztrZH4AytTHxVvHVgjPvTnT",
                'transaction_id' => "a51cfcbb-423a-4652-bffd-8be29ec04703",
                'private_money_id' => "87692541-8d1f-4ac7-bbf8-9e85ca714d92",
                'is_modified' => TRUE,
                'transaction_types' => ["transfer", "payment", "exchange", "topup", "cashback"],
                'next_page_cursor_id' => "856cf546-58c2-43fa-bd53-5bc2785125a7",
                'prev_page_cursor_id' => "1c8654e4-15dc-453a-8e85-6cffcc5c11b9",
                'per_page' => 917,
                'transfer_types' => ["exchange", "payment"],
                'description' => "Ml90EeuZgaP20pyyEjfyZnRCBHpzVqBZqNRFUo9BhqQxq9FR8VF2gH7EAnlFEgMmyi8jmBN0T80aLvrKoRyTXgPVT4Az",
                'from' => "2023-03-20T22:21:25.000000Z",
                'to' => "2023-09-10T15:40:12.000000Z"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
