<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class RefundExternalTransaction extends TestCase
{
    public function testRefundExternalTransaction0()
    {
        $client = $this->newClient();
        $request = new Request\RefundExternalTransaction(
            "dbad9ea3-287a-46f6-8438-7e0dab5f6223"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testRefundExternalTransaction1()
    {
        $client = $this->newClient();
        $request = new Request\RefundExternalTransaction(
            "dbad9ea3-287a-46f6-8438-7e0dab5f6223",
            [
                'description' => "TjKb1dIcQKtgPEpt9Ynsu0LI4T70lQwB453YpOK96EoFGxVJNTeRlFM4Xw2YneFRtau24yc1kusN7qW2yhhPFbHNPhRgnqYnUlh4JbOrMj5jFwrAdcz57ZOWsDr0Djt9M12BOno1AcjM96oft"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
