<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class RefundExternalTransaction extends TestCase
{
    public function testRefundExternalTransaction0()
    {
        $client = $this->newClient();
        $request = new Request\RefundExternalTransaction(
            "67ec1659-037f-45c5-9988-08fa42cdeca7"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testRefundExternalTransaction1()
    {
        $client = $this->newClient();
        $request = new Request\RefundExternalTransaction(
            "67ec1659-037f-45c5-9988-08fa42cdeca7",
            [
                'description' => "RwGMcnoMIx2DGcYTgqWcyKj7AaZOfsYSyeeckdWD6AmukIbvyJRzO0owQXK0VfdA"
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
