<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class RequestUserStats extends TestCase
{
    public function testRequestUserStats0()
    {
        $client = $this->newClient();
        $request = new Request\RequestUserStats(
            "2024-02-01T13:18:04.000000Z",
            "2024-11-06T07:17:09.000000Z"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
