<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class UpdateCashtray extends TestCase
{
    public function testUpdateCashtray0()
    {
        $client = $this->newClient();
        $request = new Request\UpdateCashtray(
            "931046a9-0056-4e6a-a929-9e7f7a878001"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testUpdateCashtray1()
    {
        $client = $this->newClient();
        $request = new Request\UpdateCashtray(
            "931046a9-0056-4e6a-a929-9e7f7a878001",
            [
                'expires_in' => 4425
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testUpdateCashtray2()
    {
        $client = $this->newClient();
        $request = new Request\UpdateCashtray(
            "931046a9-0056-4e6a-a929-9e7f7a878001",
            [
                'description' => "qO1OToomGXyw7qk2DIJM8AhArP4D8wQVUv0Izvao2vedRz5Rr5ZAw8kV9ePosTic8pUXqXhqbYvbrbwkQSFM3axtTEd7Wl2VRPJxNbfaffcymGdGjX2HTTdaut",
                'expires_in' => 4219
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testUpdateCashtray3()
    {
        $client = $this->newClient();
        $request = new Request\UpdateCashtray(
            "931046a9-0056-4e6a-a929-9e7f7a878001",
            [
                'amount' => 5351.0,
                'description' => "99kBtkdr0VHFRrerR0OfWtsGXEEjyTRIHnR9U1e7FtHbyUFu4q9qtcuhM8ObigPTj5",
                'expires_in' => 5178
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
