<?php
// DO NOT EDIT: File is generated by code generator.
namespace Pokepay;

class UpdateAccount extends TestCase
{
    public function testUpdateAccount0()
    {
        $client = $this->newClient();
        $request = new Request\UpdateAccount(
            "5cfe4fb7-7fd3-43bc-80d6-5b589afc5559"
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testUpdateAccount1()
    {
        $client = $this->newClient();
        $request = new Request\UpdateAccount(
            "5cfe4fb7-7fd3-43bc-80d6-5b589afc5559",
            [
                'can_transfer_topup' => FALSE
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testUpdateAccount2()
    {
        $client = $this->newClient();
        $request = new Request\UpdateAccount(
            "5cfe4fb7-7fd3-43bc-80d6-5b589afc5559",
            [
                'status' => "pre-closed",
                'can_transfer_topup' => TRUE
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
    public function testUpdateAccount3()
    {
        $client = $this->newClient();
        $request = new Request\UpdateAccount(
            "5cfe4fb7-7fd3-43bc-80d6-5b589afc5559",
            [
                'is_suspended' => FALSE,
                'status' => "pre-closed",
                'can_transfer_topup' => FALSE
            ]
        );
        try {
            $response = $client->send($request);
            $this->assertTrue(true);
        } catch (Error\HttpRequest $e) {
            $this->assertNotSame(400, $e->code);
        } catch (Error\ApiConnection $e) {
            $this->assertTrue(false);
        }
    }
}
