<?php
// DO NOT EDIT: File is generated by code generator.

namespace Pokepay\Request;


class ActivateUserDevice extends Base
{
    protected $method = 'POST';
    public $responseClass = \Pokepay\Response\UserDevice::class;
    private $userDeviceId;
    public function __construct($userDeviceId)
    {
        parent::__construct();
        $this->userDeviceId = $userDeviceId;

        $this->optionalParams = array();
    }

    public function getPath()
    {
        return '/user-devices' . '/' . $this->userDeviceId . '/activate';
    }

    public function getParams()
    {
        $params = array(
            
        );

        $params += $this->optionalParams;

        
        return $params;
    }
}
