<?php
// DO NOT EDIT: File is generated by code generator.

namespace Pokepay\Request;


class BulkCreateTransaction extends Base
{
    protected $method = 'POST';
    public $responseClass = \Pokepay\Response\BulkTransaction::class;
    private $name;
    private $content;
    private $requestId;
    public function __construct($name, $content, $requestId, $optionalParams = array())
    {
        parent::__construct();
        $this->name = $name;
        $this->content = $content;
        $this->requestId = $requestId;

        $this->optionalParams = $optionalParams;
    }

    public function getPath()
    {
        return '/transactions/bulk';
    }

    public function getParams()
    {
        $params = array(
            'name' => $this->name,
            'content' => $this->content,
            'request_id' => $this->requestId,
        );

        $params += $this->optionalParams;

        
        return $params;
    }
}
