<?php
// DO NOT EDIT: File is generated by code generator.

namespace Pokepay\Request;


class CreateCustomerCard extends Base
{
    protected $method = 'POST';
    public $responseClass = \Pokepay\Response\UserCard::class;
    private $customerId;
    private $token;
    public function __construct($customerId, $token, $optionalParams = array())
    {
        parent::__construct();
        $this->customerId = $customerId;
        $this->token = $token;

        $this->optionalParams = $optionalParams;
    }

    public function getPath()
    {
        return '/customers' . '/' . $this->customerId . '/cards';
    }

    public function getParams()
    {
        $params = array(
            'token' => $this->token,
        );

        $params += $this->optionalParams;

        
        return $params;
    }
}
