<?php
// DO NOT EDIT: File is generated by code generator.

namespace Pokepay\Response;

use DateTimeZone;

class CreditSession extends Base
{
    /**
     * @var string
     */
    public $id;
    /**
     * @var \DateTime
     */
    public $expiresAt;

    protected function normalize($timezone)
    {
        $tz = new DateTimeZone($timezone);
        $this->expiresAt->setTimezone($tz);
    }
}
