<?php
// DO NOT EDIT: File is generated by code generator.

namespace Pokepay\Response;


class PaginatedAccounts extends PaginatedRows
{
    /**
     * @var Account[]
     */
    public $rows;
    /**
     * @var integer
     */
    public $count;
    /**
     * @var Pagination
     */
    public $pagination;
}
